export const DUMMY_POSTS = [
    // React Posts
    {
      id: '1',
      img: 'https://via.placeholder.com/150',
      category: 'React',
      title: 'Understanding React Hooks',
      desc: 'Learn how to simplify state management and side effects with React Hooks.',
      authorID: '101',
      authorName: 'Ovi',
      readTime: '5 min read',
      date: '2024-12-10',
    },
    {
      id: '2',
      img: 'https://via.placeholder.com/150',
      category: 'React',
      title: 'React Router: A Comprehensive Guide',
      desc: 'Master navigation in React applications with React Router.',
      authorID: '102',
      authorName: 'Ovi',
      readTime: '7 min read',
      date: '2024-12-11',
    },
    {
      id: '3',
      img: 'https://via.placeholder.com/150',
      category: 'React',
      title: 'Optimizing React Performance',
      desc: 'Tips and tricks to make your React app blazing fast.',
      authorID: '103',
      authorName: 'Ovi',
      readTime: '6 min read',
      date: '2024-12-12',
    },
    {
      id: '4',
      img: 'https://via.placeholder.com/150',
      category: 'React',
      title: 'Top React Component Libraries',
      desc: 'Explore the best libraries to speed up React development.',
      authorID: '104',
      authorName: 'Ovi',
      readTime: '4 min read',
      date: '2024-12-13',
    },
    {
      id: '5',
      img: 'https://via.placeholder.com/150',
      category: 'React',
      title: 'State Management with Redux and Context',
      desc: 'A comparison of Redux and React Context API for state management.',
      authorID: '105',
      authorName: 'Ovi',
      readTime: '8 min read',
      date: '2024-12-14',
    },
  
    // Node Posts
    {
      id: '6',
      img: 'https://via.placeholder.com/150',
      category: 'Node',
      title: 'Getting Started with Node.js',
      desc: 'A beginner’s guide to Node.js and its ecosystem.',
      authorID: '201',
      authorName: 'Ovi',
      readTime: '6 min read',
      date: '2024-12-10',
    },
    {
      id: '7',
      img: 'https://via.placeholder.com/150',
      category: 'Node',
      title: 'Building a REST API with Node.js',
      desc: 'Learn how to create a RESTful API using Node.js and Express.',
      authorID: '202',
      authorName: 'Ovi',
      readTime: '9 min read',
      date: '2024-12-11',
    },
    {
      id: '8',
      img: 'https://via.placeholder.com/150',
      category: 'Node',
      title: 'Event Loop Explained',
      desc: 'Dive deep into Node.js’s event-driven architecture.',
      authorID: '203',
      authorName: 'Ovi',
      readTime: '7 min read',
      date: '2024-12-12',
    },
    {
      id: '9',
      img: 'https://via.placeholder.com/150',
      category: 'Node',
      title: 'Node.js Streams in Action',
      desc: 'Leverage streams for efficient data processing in Node.js.',
      authorID: '204',
      authorName: 'Ovi',
      readTime: '5 min read',
      date: '2024-12-13',
    },
    {
      id: '10',
      img: 'https://via.placeholder.com/150',
      category: 'Node',
      title: 'Best Practices for Node.js Developers',
      desc: 'Tips and techniques to write cleaner and faster Node.js code.',
      authorID: '205',
      authorName: 'Ovi',
      readTime: '6 min read',
      date: '2024-12-14',
    },
  
    // Express Posts
    {
      id: '11',
      img: 'https://via.placeholder.com/150',
      category: 'Express',
      title: 'Getting Started with Express.js',
      desc: 'Learn the basics of Express.js to build web applications.',
      authorID: '301',
      authorName: 'Ovi',
      readTime: '5 min read',
      date: '2024-12-10',
    },
    {
      id: '12',
      img: 'https://via.placeholder.com/150',
      category: 'Express',
      title: 'Middleware in Express.js Explained',
      desc: 'Understand how middleware works and how to use it in Express.',
      authorID: '302',
      authorName: 'Ovi',
      readTime: '7 min read',
      date: '2024-12-11',
    },
    {
      id: '13',
      img: 'https://via.placeholder.com/150',
      category: 'Express',
      title: 'Error Handling in Express.js',
      desc: 'A guide to handling errors effectively in your Express apps.',
      authorID: '303',
      authorName: 'Ovi',
      readTime: '6 min read',
      date: '2024-12-12',
    },
    {
      id: '14',
      img: 'https://via.placeholder.com/150',
      category: 'Express',
      title: 'Express.js Routing Basics',
      desc: 'Learn how to manage routes and controllers in Express.',
      authorID: '304',
      authorName: 'Ovi',
      readTime: '4 min read',
      date: '2024-12-13',
    },
    {
      id: '15',
      img: 'https://via.placeholder.com/150',
      category: 'Express',
      title: 'Building Secure Applications with Express.js',
      desc: 'Explore security best practices for Express applications.',
      authorID: '305',
      authorName: 'Ovi',
      readTime: '8 min read',
      date: '2024-12-14',
    },
  
    // MongoDB Posts
    {
      id: '16',
      img: 'https://via.placeholder.com/150',
      category: 'MongoDB',
      title: 'Getting Started with MongoDB',
      desc: 'An introduction to MongoDB and NoSQL databases.',
      authorID: '401',
      authorName: 'Ovi',
      readTime: '5 min read',
      date: '2024-12-10',
    },
    {
      id: '17',
      img: 'https://via.placeholder.com/150',
      category: 'MongoDB',
      title: 'CRUD Operations in MongoDB',
      desc: 'Learn how to perform Create, Read, Update, and Delete operations.',
      authorID: '402',
      authorName: 'Ovi',
      readTime: '6 min read',
      date: '2024-12-11',
    },
    {
      id: '18',
      img: 'https://via.placeholder.com/150',
      category: 'MongoDB',
      title: 'Indexing in MongoDB for Performance',
      desc: 'Boost MongoDB performance with efficient indexing.',
      authorID: '403',
      authorName: 'Ovi',
      readTime: '7 min read',
      date: '2024-12-12',
    },
    {
      id: '19',
      img: 'https://via.placeholder.com/150',
      category: 'MongoDB',
      title: 'Aggregation Framework in MongoDB',
      desc: 'Understand and use the powerful aggregation framework.',
      authorID: '404',
      authorName: 'Ovi',
      readTime: '8 min read',
      date: '2024-12-13',
    },
    {
      id: '20',
      img: 'https://via.placeholder.com/150',
      category: 'MongoDB',
      title: 'Securing MongoDB Databases',
      desc: 'Best practices to keep your MongoDB data secure.',
      authorID: '405',
      authorName: 'Ovi',
      readTime: '6 min read',
      date: '2024-12-14',
    },
  ];